### ISSUE TITLE
MCA 5.1.2-1.9 | Bug and Incompatibility

### ISSUE THREAD

**Issue by The-Euphoria** [WildBamaBoy/minecraft-comes-alive#690] opened 2016-04-24 09:58 UTC
Hello MCA Dev Team,

I've been testing the new latest and greatest 5.1.2 version of MCA for 1.9, when I noticed a bug and an incompatibility.

**The Bug:**

All villagers have the same trades. There seems to be only 2 variants, the first set of trades start "Wool = Emerald" and the second set of trades starts "Wheat = Emeralds", but these are the only 2.

I even spawned in around 60-70 new villagers and they still all had the same 2 trade sets.

**The Incompatibility:**

I use a popular mod called RTG (Realistic Terrain Generation). One of the features RTG has, you can edit the config to de/increase the size and frequency of vanilla villages. It does Not change or edit the villages or villagers in any way, it just de/increases the spawn chance of a village and how many buildings spawn.

I have my world set so villages are really quite rare and hard to find, but when you do find them they are 3-4 times normal vanilla size.

Sadly, MCA for 1.9 now overrides this and all villages have gone to standard. I used to use these 2 mods together a while ago and I'm sure MCA didn't have an issue back then.

Anyway, is that something you would need to patch, or is it something I could do with config edits or something???

Thanks for you help, and massive thank you for the 1.9 update. I truly have missed MCA :)

**Comment by mezzodrinker** [comment] 2016-04-24 13:48
MCA doesn't change anything about world generation, so the cause of the incorrect generation probably lies in a different mod (maybe even RTG itself).

**Comment by The-Euphoria** [comment] 2016-04-24 15:02
Oh :confused: Then I am confused, because I started 4 new worlds with all my mod including RTG to test some things, then as soon as I added MCA, all the villages were small (Vanilla) sized and quite frequent and easy to find.
So I tried again with removing MCA, and sure enough, all villages were large and very few and far between.

**Comment by mezzodrinker** [comment] 2016-04-24 15:03
Hmm, that doesn't make any sense...

**Comment by The-Euphoria** [comment] 2016-04-24 18:26
**[Update To The RTG Incompatibility]**

Really weird update to this story. So I tested RTG with MCA again this evening, and again, and again... But every time all villages went back to Vanilla size and frequency.

So I tried increasing the village sizes even more... a Lot more. With the setting I used, villages should be like cities, 50-100 buildings. I started a new world with RTG and MCA again, found a village but it was tiny, even small for a vanilla village. So I tried increasing the frequency at which they generate, started a new world with RTG and MCA installed and Bang! Huge massive villages everywhere, 4 huge village cities just within my render distance! So we are getting somewhere I thought... More testing needed.

I tried reducing the frequency again, bit by bit I lowered the setting and sure enough villages were rarer and hard to find, but still large when I did find one :confused: 

So the conclusion seems to be, very weirdly, that changing the RTG village config setting to a crazy high amount, somehow "Don't ask me how or why" stopped whatever issue these 2 mods were having and they started working together just fine.

Very strange and weird no idea how that could have effected things, but I'm not going to complain nor argue, as 2 of my favourite mods are playing nicely together again :smiley: 

Now it's just the trading bug left to squash.

**Comment by Galindorf** [comment] 2016-04-25 15:35
Hey! For the trading thing, you may want to check out the issue I am having: 
[Villager Trades Not Opening Up](https://github.com/WildBamaBoy/minecraft-comes-alive/issues/687)
I went through a bunch of villagers and made note of what trades they have, it might be helpful?
~G

**Comment by WildBamaBoy** [comment] 2016-05-04 19:54
Fixed, will be in full release of MCA for 1.9

**Closed by WildBamaBoy** 2016-05-04 19:54 UTC
