### ISSUE TITLE
[MC 1.12.2] [SpongeForge 2983] [Forge 2611] Time Out on server w/ MCA-1.12.x-5.3.1-universal.jar

### ISSUE THREAD

**Issue by Excaliburning** [WildBamaBoy/minecraft-comes-alive#1007] opened 2018-03-25 17:16 UTC
Hi !

For some reason, everything seemed to worked, server booted nicely. But once everything loaded, at the end (after saying the "Done" signaling the end of the boot) the server console keeps spouting something. I don't know where this message starts or ends so I took a whole bunch of it, sorry for the annoyance.

I'm using spongeforge-1.12.2-2611-7.1.0-BETA-2983 with 1.12.2-forge1.12.2-14.23.2.2611

I don't really "crash" when trying to join the server. I only time out. But this message keeps repeating itself without end.

I also used : CodeChickenLib-1.12.2-3.1.6.339-universal ; Farseek-1.12-2.2.4 ; FullscreenWindowed-1.12-1.6.0 ; jei_1.12.2-4.8.5.159 ; journeymap-1.12.2-5.5.2 ; **MCA-1.12.x-5.3.1-universal** ; **millenaire-6.2.0-beta.18** ; NotEnoughItems-1.12.2-2.4.1.233-universal ; **RadixCore-1.12.x-2.2.1-universal** ; **spongeforge-1.12.2-2611-7.1.0-BETA-2983** ; Streams-1.12-0.4.3 ; Uppers-0.0.4 ; WorldEdit+CUI+Forge+Edition+2-2.1.2-mf-1.12-14.21.1.2387 ; worldedit-forge-mc1.12-6.1.8-dist

I was in the process of testing compatibility/stability of mods when it happened. Everything was running fine, Millénaire is said to be compatible with MCA so I added both at the same time (with RadixCore for MCA). Before adding these 3 .jar everything ran smooth. When I added Millénaire and MCA, the server took more than 10 minutes to boot (I'm not that surprised, I deleted the old world so it had to gen a new one, Millénaire and MCA also add a lot of population things so I expected a long boot). Then, I couldn't connect being timed out every time. I see that MCA seems to be at fault for some reason since the error starts with "[mca.*]".

For now I'll get rid of MCA but I'd love to be able to play with it. If you have any fix for that, I'm all ears. Thanks for taking some time about it.

**Here are the error logs:**
https://gist.github.com/Excaliburning/617464c6947ca3705f7f328227d67780

*edit: created a gist instead of throwing everything here.*

**Comment by TimOverboard** [comment] 2018-08-08 18:44
I am having this same issue using sponge + forge 2705.

It seems to be connected to game saving, which is why everything feels fine for a bit.
I'm adding this just to help anyone who is looking here.. I have no answers I'm afraid.

Further to it, if I implement this on a running server, the clients crash when they approach villagers and MCA is trying to convert them. the server stays up, but it cant save the entities properly. If clients log back in they see mostly invisible villagers all called steve..

**Comment by Excaliburning** [comment] 2018-08-08 21:57
Thanks @DrDaymaker for your addition to the thread !

I no longer run the server (we got busy, made a back-up for later, etc, thing won't run before November at the very least) so I can't test it again in the same environment nor in an updated environment.
Maybe my exact issue have been resolved with a Sponge update or MCA update (if any ?). I can't tell.

I'll update this whenever possible to know if the issue is still on-going on our setup, however this will take time as we don't plan on running it soon as I said before. Could you provide a crash log and/or server log that may help to identify this issue ?

**Comment by TimOverboard** [comment] 2018-08-10 03:17
indeed sponge literally just made a workaround I think this week :)

For info to anyone, sponge/global.conf now has a setting to "fix broken mods" which is simply referring to something about them using raw netty methods? I dunno java sucks.. 

you have to add "mca" to the list of broken mods. Funny cos it was working until sponge came along... Dont worry about what a list looks like, the config file cleans itself up.

Having said that the latest versions of spongeforge make a real noticeable difference to me in terms of speed and latency. (currently using spongeforge3377)

**Comment by Excaliburning** [comment] 2018-08-10 11:42
Interesting ! Thanks for sharing this, it could be of great help.
After adding MCA to the list of broken mods, do MCA work as intended ? Any missing features ?
I'm happy to know Sponge worked on speed and latency since these were things that got hit hard before (we had so many mods on our server a friend with a bad computer couldn't even connect).

**Comment by TimOverboard** [comment] 2019-04-11 21:44
Ok a bit necro this but anyways... some useful info maybe I hope.

I'd never used MCA before so couldn't say how much was working but once
villages were "converted" all seemed fully functional.. bear in mind this
is on a world first created in 1.9.

I even spawned a few into a minecolony, which worked really well, actually.

But the server still seemed overloaded.  I now come to what makes this
necro worthwhile .. so I decided to actually look at the running profile ..
"spark" is an amazing sponge plugin. If you've not got it then get it.
Truly.. instant data on what your server is spending its time doing.

In my case it was spending like 50% of every tick doing entity updates of
MCA villages. Its the entity activation range,  see.

I don't see much fun in them only living whilst u r there... so I removed
the limit in sponge config.  But without a player around u get no mobs, so
after a while I had some very densely populated villages indeed! And it's
not a small map, with quite a few villages..

I thought briefly about trying to sort out a way to isolate player's "home"
village villagers from entity activation range so unattached villages could
lie dormant, but then life reminded I didn't have time for this sort of
thing.

I think implmenting this feature (or another solution) is an essential
requirement for this mod to be used on a multiplayer server. Imo of course.

But sponge + MCA worked fine, I reckon can close this XD

On 10 Aug 2018 12:42, "Shin Taillelaine" <notifications@github.com> wrote:

Interesting ! Thanks for sharing this, it could be of great help.
After adding MCA to the list of broken mods, do MCA work as intended ? Any
missing features ?
I'm happy to know Sponge worked on speed and latency since these were
things that got hit hard before (we had so many mods on our server a friend
with a bad computer couldn't even connect).

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/WildBamaBoy/minecraft-comes-alive/issues/1007#issuecomment-412058382>,
or mute the thread

**Comment by Excaliburning** [comment] 2019-04-12 17:46
Spark is indeed incredible and a must have for any admin purposes.
I'm glad to see MCA and Sponge getting along now, I have no idea what happened between now and then as I was away for a long time (even longer when considering Minecraft only).
I guess I will try it again the next time we get ourselves a server ! I'm not sure if this can be closed but considering the many updates that happened, it's at least probable that the issue is out-of-date and possibly solved.

**Closed as completed** 2019-06-02 02:57 UTC
