### ISSUE TITLE
[Forge MP 1.12.2 #2582] Crash 'java.lang.Float cannot be cast to java.lang.Boolean'

### ISSUE THREAD

**Issue by t3f** [WildBamaBoy/minecraft-comes-alive#947] opened 2017-12-27 19:46 UTC
Numerous client crashes on server instance affecting folks getting near villages.  At this point MCA is being very unsafe.

```
Description: Rendering entity in world

java.lang.ClassCastException: java.lang.Float cannot be cast to java.lang.Boolean
	at mca.actions.AbstractToggleAction.getIsActive(AbstractToggleAction.java:41)
	at mca.entity.VillagerBehaviors.isToggleActionActive(VillagerBehaviors.java:139)
	at mca.client.render.RenderVillagerMCA.doRenderEffects(RenderVillagerMCA.java:172)
	at mca.client.render.RenderVillagerMCA.doRender(RenderVillagerMCA.java:367)
	at mca.client.render.RenderVillagerMCA.func_76986_a(RenderVillagerMCA.java:34)
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:384)
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:368)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:628)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1345)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1062)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```
Full Crashdump:
[crash-2017-12-27_12.45.01-client.txt](https://github.com/WildBamaBoy/minecraft-comes-alive/files/1589733/crash-2017-12-27_12.45.01-client.txt)

**Comment by SDPhantom** [comment] 2017-12-29 10:01
Duplicate of #884

**Closed as completed** 2018-01-28 08:28 UTC
