### ISSUE TITLE
[Forge MP 1.12.2 #2582] Crash 'com.google.common.base.Present cannot be cast to java.lang.Boolean'

### ISSUE THREAD

**Issue by t3f** [WildBamaBoy/minecraft-comes-alive#948] opened 2017-12-27 19:49 UTC
I have number of users with client side crash approaching MCA villages on MP Server similar to this.

```
Description: Ticking entity

java.lang.ClassCastException: com.google.common.base.Present cannot be cast to java.lang.Boolean
	at mca.actions.ActionProcreate.getIsProcreating(ActionProcreate.java:112)
	at mca.actions.ActionProcreate.onUpdateClient(ActionProcreate.java:38)
	at mca.entity.VillagerBehaviors.onUpdate(VillagerBehaviors.java:90)
	at mca.entity.EntityVillagerMCA.func_70071_h_(EntityVillagerMCA.java:178)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1845)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

Example Full Dump:
[crash-2017-12-27_12.54.36-client.txt](https://github.com/WildBamaBoy/minecraft-comes-alive/files/1589738/crash-2017-12-27_12.54.36-client.txt)

**Comment by SDPhantom** [comment] 2017-12-29 09:54
Duplicate of #910

**Comment by VirtualGaming1** [comment] 2018-01-08 11:03
Duplicate of #884

**Closed as completed** 2018-01-28 08:27 UTC
