### ISSUE TITLE
Crash After Extra Planets Atomic Bomb Detonation

### ISSUE THREAD

**Issue by frqnny** [WildBamaBoy/minecraft-comes-alive#1157] opened 2019-06-19 20:30 UTC
Extra Planets adds an "atomic bomb" which gives off a big explosion. 
I set it off in the middle of a village- and got this crash. 
https://paste.dimdev.org/cazaxarofe.mccrash
Ticking Entity!!

hope this helps

**Comment by WildBamaBoy** [comment] 2019-06-25 01:21
Dupe of #1155

**Closed as completed by WildBamaBoy** 2019-06-25 01:21 UTC
