### ISSUE TITLE
1.10.2 Ticking Entity Fishing Chore

### ISSUE THREAD

**Issue by captcookie** [WildBamaBoy/minecraft-comes-alive#747] opened 2016-07-11 04:35 UTC
Long story short... my daughter was given a fishing chore. When I logged and return, the server crashed at least twice and refused to let me login. 

---- Minecraft Crash Report ----

WARNING: coremods are present:
  IC2core (industrialcraft-2-2.6.10-ex110.jar)
  CXLibraryCore (cxlibrary-1.10.2-1.2.2.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.38-beta.jar)
  ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.0.jar)
Contact their authors BEFORE contacting forge

// I'm sorry, Dave.

Time: 7/11/16 4:25 AM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at mca.entity.EntityChoreFishHook.func_70071_h_(EntityChoreFishHook.java:193)
	at net.minecraft.world.World.func_72866_a(World.java:1962)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:837)
	at net.minecraft.world.World.func_72870_g(World.java:1932)
	at net.minecraft.world.World.func_72939_s(World.java:1748)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:618)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at mca.entity.EntityChoreFishHook.func_70071_h_(EntityChoreFishHook.java:193)
	at net.minecraft.world.World.func_72866_a(World.java:1962)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:837)
	at net.minecraft.world.World.func_72870_g(World.java:1932)

-- Entity being ticked --
Details:
	Entity Type: MCA.EntityChoreFishHook (mca.entity.EntityChoreFishHook)
	Entity ID: 579
	Entity Name: entity.MCA.EntityChoreFishHook.name
	Entity's Exact location: -2016.43, 65.56, 3945.25
	Entity's Block location: World: (-2017,65,3945), Chunk: (at 15,4,9 in -127,246; contains blocks -2032,0,3936 to -2017,255,3951), Region: (-4,7; contains chunks -128,224 to -97,255, blocks -2048,0,3584 to -1537,255,4095)
	Entity's Momentum: -0.22, -0.30, 0.51
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1748)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:618)

-- Affected level --
Details:
	Level name: world
	All players: 1 total; [EntityPlayerMP['rynzii15'/550, l='world', x=-1968.87, y=73.00, z=3978.06]]
	Chunk stats: ServerChunkCache: 384 Drop: 0
	Level seed: 4298403334453956052
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-525,70,268), Chunk: (at 3,4,12 in -33,16; contains blocks -528,0,256 to -513,255,271), Region: (-2,0; contains chunks -64,0 to -33,31, blocks -1024,0,0 to -513,255,511)
	Level time: 2346061 game time, 165660 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 89757 (now: false), thunder time: 114417 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Linux (amd64) version 3.13.0-87-generic
	Java Version: 1.8.0_91, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 471643592 bytes (449 MB) / 1395658752 bytes (1331 MB) up to 6372720640 bytes (6077 MB)
	JVM Flags: 4 total; -Xmx6144M -Xms128M -XX:MaxMetaspaceSize=256M -XX:+UseConcMarkSweepGC
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.32 Powered by Forge 12.18.0.2010 81 mods loaded, 81 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-12.18.0.2010.jar) 
	UCHIJAAAA	Forge{12.18.0.2010} [Minecraft Forge] (forge-12.18.0.2010.jar) 
	UCHIJAAAA	Baubles{1.2.1.0} [Baubles] (Baubles-1.9.4-1.2.1.0.jar) 
	UCHIJAAAA	betterbuilderswands{0.6.5} [Better Builder's Wands] (BetterBuildersWands-0.6.5-1.10r138+8595fc7.jar) 
	UCHIJAAAA	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.10-alpha-1.0.0.jar) 
	UCHIJAAAA	JEI{3.7.5.227} [Just Enough Items] (jei_1.10.2-3.7.5.227.jar) 
	UCHIJAAAA	BloodMagic{1.9.4-2.0.2-50} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.9.4-2.0.2-50.jar) 
	UCHIJAAAA	BloodArsenal{1.9.4-2.0.0-10} [Blood Arsenal] (BloodArsenal-1.9.4-2.0.0-10.jar) 
	UCHIJAAAA	boilerplate{1.9.4-8.2.3} [Boilerplate] (Boilerplate-1.9.4-8.2.3-universal.jar) 
	UCHIJAAAA	Botania{r1.8-312} [Botania] (Botania-unofficial.r1.8-312.jar) 
	UCHIJAAAA	Chameleon{1.9.4-2.1.5} [Chameleon] (Chameleon-1.9.4-2.1.5.jar) 
	UCHIJAAAA	mcmultipart{1.2.0} [MCMultiPart] (MCMultiPart-1.2.0-universal.jar) 
	UCHIJAAAA	CharsetLib{0.3.0-pre12} [‽] (Charset-0.3.0-pre12.jar) 
	UCHIJAAAA	CharsetAudio{0.3.0-pre12} [♫] (Charset-0.3.0-pre12.jar) 
	UCHIJAAAA	CharsetCarts{0.3.0-pre12} [U] (Charset-0.3.0-pre12.jar) 
	UCHIJAAAA	CharsetDecoration{0.3.0-pre12} [�?] (Charset-0.3.0-pre12.jar) 
	UCHIJAAAA	CharsetDrama{0.3.0-pre12} [!] (Charset-0.3.0-pre12.jar) 
	UCHIJAAAA	CharsetFarming{0.3.0-pre12} [;] (Charset-0.3.0-pre12.jar) 
	UCHIJAAAA	CharsetGates{0.3.0-pre12} [&] (Charset-0.3.0-pre12.jar) 
	UCHIJAAAA	CharsetPipes{0.3.0-pre12} [|] (Charset-0.3.0-pre12.jar) 
	UCHIJAAAA	CharsetStorage{0.3.0-pre12} [#] (Charset-0.3.0-pre12.jar) 
	UCHIJAAAA	CharsetTweaks{0.3.0-pre12} [*] (Charset-0.3.0-pre12.jar) 
	UCHIJAAAA	CharsetWires{0.3.0-pre12} [+] (Charset-0.3.0-pre12.jar) 
	UCHIJAAAA	CharsetWrench{0.3.0-pre12} [/] (Charset-0.3.0-pre12.jar) 
	UCHIJAAAA	chisel{@VERSION@} [Chisel] (Chisel-MC1.9.4-0.0.5.29.jar) 
	UCHIJAAAA	chiselsandbits{11.5} [Chisels & Bits] (chiselsandbits-11.5.jar) 
	UCHIJAAAA	ComputerCraft{1.80pr0} [ComputerCraft] (ComputerCraft1.80pr0.jar) 
	UCHIJAAAA	cookingforblockheads{3.1.26} [Cooking for Blockheads] (CookingForBlockheads-mc1.9.4-3.1.26.jar) 
	UCHIJAAAA	cxlibrary{1.2.2} [CXLibrary] (cxlibrary-1.10.2-1.2.2.jar) 
	UCHIJAAAA	cyclopscore{0.7.1} [Cyclops Core] (CyclopsCore-1.9.4-0.7.1.jar) 
	UCHIJAAAA	EnderBags{2.0.1} [EnderBags] (EnderBags-1.9.4-2.0.0.jar) 
	UCHIJAAAA	endercore{1.10.2-0.4.1.38-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.38-beta.jar) 
	UCHIJAAAA	EnderIO{1.10.2-3.0.1.64_beta} [Ender IO] (EnderIO-1.10.2-3.0.1.64_beta.jar) 
	UCHIJAAAA	shetiphiancore{3.3.0} [ShetiPhian-Core] (shetiphiancore-1.10.0-3.3.0.jar) 
	UCHIJAAAA	endertanks{1.4.0} [EnderTanks] (endertanks-1.10.0-1.4.0.jar) 
	UCHIJAAAA	evilcraft{0.10.4} [EvilCraft] (EvilCraft-1.9.4-0.10.4.jar) 
	UCHIJAAAA	expandablebackpack{1.0} [Expandable Backpacks] (expandableBackpacks1.1.4_hotfix-1.10.2.jar) 
	UCHIJAAAA	ezstorage{2.1.0} [EZ Storage 2] (ezstorage-2.1.0.jar) 
	UCHIJAAAA	fe{1.2.1} [Food Expansion] (FoodExpansion1.2.3-1.10.2.jar) 
	UCHIJAAAA	forestry{5.1.10.192} [Forestry] (forestry_1.10.2-5.1.10.192.jar) 
	UCHIJAAAA	ftbl{2.1.0} [FTBLib] (FTBLib-1.9.4-2.1.0-pre2.jar) 
	UCHIJAAAA	ftbu{2.1.0} [FTBUtilities] (FTBUtilities-1.9.4-2.1.0-pre2.jar) 
	UCHIJAAAA	furnus{1.83} [Furnus] (Furnus-1.9.4-1.83.jar) 
	UCHIJAAAA	lit{@VERSION@} [Little Insignificant Things] (LittleInsignificantThings-1.10-3.0.2.jar) 
	UCHIJAAAA	SilentLib{1.0.11} [Silent Lib] (SilentLib-1.9.4-1.0.11-19.jar) 
	UCHIJAAAA	SilentGems{2.0.22} [Silent's Gems] (SilentsGems-1.10.2-2.0.22-51.jar) 
	UCHIJAAAA	gemulation{1.10-4.0.0} [Gemulation] (Gemulation-1.10-4.0.0.jar) 
	UCHIJAAAA	gravestone{1.5.0} [Gravestone] (Gravestone Mod 1.5.0.jar) 
	UCHIJAAAA	IC2{2.6.10-ex110} [IndustrialCraft 2] (industrialcraft-2-2.6.10-ex110.jar) 
	UCHIJAAAA	IronChest{7.0.5.793} [Iron Chest] (ironchest-1.10-7.0.5.793.jar) 
	UCHIJAAAA	mantle{1.10-0.10.3.jenkins156} [Mantle] (Mantle-1.10-0.10.3.jar) 
	UCHIJAAAA	RadixCore{1.10.2-2.1.2} [RadixCore] (RadixCore-1.10.2-2.1.2-universal.jar) 
	UCHIJAAAA	MCA{1.10.2-5.2.0} [Minecraft Comes Alive] (MCA-1.10.2-5.2.0-universal.jar) 
	UCHIJAAAA	modularutilities{1.9.4-0.2.2} [Modular Utilities] (ModularUtilities-1.9.4-0.2.2.jar) 
	UCHIJAAAA	MoreFurnaces{1.8.1} [More Furnaces] (MoreFurnaces-1.10-1.8.1.jar) 
	UCHIJAAAA	Morpheus{1.10-3.1.6} [Morpheus] (Morpheus-1.10-3.1.6.jar) 
	UCHIJAAAA	multibeds{1.2.0} [Multi-Beds] (multibeds-1.10.0-1.2.0.jar) 
	UCHIJAAAA	terraqueous{1.2.0} [Terraqueous] (terraqueous-1.10.0-1.2.0.jar) 
	UCHIJAAAA	multistorage{1.2.1} [Multi-Storage] (multistorage-1.10.0-1.2.1.jar) 
	UCHIJAAAA	mysticalagriculture{1.0.0} [Mystical Agriculture] (mysticalagriculture-1.0.3.jar) 
	UCHIJAAAA	netherportalfix{1.0} [Nether Portal Fix] (netherportalfix-mc1.9.4-4.0.1.jar) 
	UCHIJAAAA	fodc{1.9.0} [Ore Dictionary Converter] (OreDictionaryConverter-1.9.0.jar) 
	UCHIJAAAA	packingtape{0.5.2} [Packing Tape] (PackingTape-1.9.4-0.5.2.jar) 
	UCHIJAAAA	harvestcraft{1.9.4-pre} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4c.jar) 
	UCHIJAAAA	parachutemod{1.5.2} [Parachute Mod] (parachutemod-ng-1.10.2-1.5.2-409.jar) 
	UCHIJAAAA	planttech{1.6.0} [Planttech] (planttech-1.6.1 - 1.10.2.jar) 
	UCHIJAAAA	platforms{1.2.0} [Platforms] (platforms-1.10.0-1.2.0.jar) 
	UCHIJAAAA	recallstones{0.6.2} [Recall Stones] (RecallStones-1.10.2-0.6.2.jar) 
	UCHIJAAAA	xreliquary{1.10.2-1.3.2.419} [Reliquary] (Reliquary-1.10.2-1.3.2.419.jar) 
	UCHIJAAAA	roots{0.107} [Roots] (roots-0.107.jar) 
	UCHIJAAAA	runesofwizardry{1.9.4-0.7.0} [Runes of Wizardry] (Runes-of-Wizardry-1.9.4-0.7.0.jar) 
	UCHIJAAAA	runesofwizardry_classics{1.9.4-0.4.0} [Runes of Wizardry - Classic Dusts Pack] (RunesofWizardry-Classics-1.9.4-0.4.0.jar) 
	UCHIJAAAA	simplebarrels{1.1a} [Simple Barrels] (simplebarrels-1.10.2-2002-1.1a.jar) 
	UCHIJAAAA	SolarFluxReborn{1.10.2_0.4b} [Solar Flux Reborn] (SolarFluxReborn-1.10.2_0.4b.jar) 
	UCHIJAAAA	StorageDrawers{1.9.4-3.1.11} [Storage Drawers] (StorageDrawers-1.9.4-3.1.11.jar) 
	UCHIJAAAA	tconstruct{1.10-2.3.3a.jenkins271} [Tinkers' Construct] (TConstruct-1.10-2.3.3a.jar) 
	UCHIJAAAA	theoneprobe{1.0.13} [The One Probe] (theoneprobe-1.10-1.0.13.jar) 
	UCHIJAAAA	waterstrainer{1.0.1} [Water Strainer] (WaterStrainer-1.9.4-1.0.1.jar) 
	UCHIJAAAA	Waypoints{1.9.4-1.2.1} [Waypoints] (waypoints-1.9.4-1.2.1.jar) 
	UCHIJAAAA	xlfoodmod{1.10.2-0.1.1} [XL Food Mod] (XL Food Mod-1.10.2-0.1.1.jar) 
	Loaded coremods (and transformers): 
IC2core (industrialcraft-2-2.6.10-ex110.jar)
  
CXLibraryCore (cxlibrary-1.10.2-1.2.2.jar)
  cubex2.cxlibrary.CoreModTransformer
EnderCorePlugin (EnderCore-1.10.2-0.4.1.38-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.0.jar)
  shetiphian.core.asm.ClassTransformer
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)

	EnderIO: No known problems detected.
	Detailed RF API diagnostics:
                  * RF API class 'EnergyStorage' is loaded from: jar:file:/home/gameservers/services/service8978/files/mods/extrautils2-1.10-alpha-1.0.0.jar!/cofh/api/energy/EnergyStorage.class
                  * RF API class 'IEnergyConnection' is loaded from: jar:file:/home/gameservers/services/service8978/files/mods/extrautils2-1.10-alpha-1.0.0.jar!/cofh/api/energy/IEnergyConnection.class
                  * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/home/gameservers/services/service8978/files/mods/extrautils2-1.10-alpha-1.0.0.jar!/cofh/api/energy/IEnergyContainerItem.class
                  * RF API class 'IEnergyHandler' is loaded from: jar:file:/home/gameservers/services/service8978/files/mods/extrautils2-1.10-alpha-1.0.0.jar!/cofh/api/energy/IEnergyHandler.class
                  * RF API class 'IEnergyProvider' is loaded from: jar:file:/home/gameservers/services/service8978/files/mods/extrautils2-1.10-alpha-1.0.0.jar!/cofh/api/energy/IEnergyProvider.class
                  * RF API class 'IEnergyReceiver' is loaded from: jar:file:/home/gameservers/services/service8978/files/mods/extrautils2-1.10-alpha-1.0.0.jar!/cofh/api/energy/IEnergyReceiver.class
                  * RF API class 'IEnergyStorage' is loaded from: jar:file:/home/gameservers/services/service8978/files/mods/extrautils2-1.10-alpha-1.0.0.jar!/cofh/api/energy/IEnergyStorage.class
                  * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/home/gameservers/services/service8978/files/mods/extrautils2-1.10-alpha-1.0.0.jar!/cofh/api/energy/ItemEnergyContainer.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/home/gameservers/services/service8978/files/mods/extrautils2-1.10-alpha-1.0.0.jar!/cofh/api/energy/TileEnergyHandler.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/home/gameservers/services/service8978/files/mods/extrautils2-1.10-alpha-1.0.0.jar!/cofh/api/energy/TileEnergyHandler.class

	Profiler Position: N/A (disabled)
	Player Count: 1 / 21; [EntityPlayerMP['rynzii15'/550, l='world', x=-1968.87, y=73.00, z=3978.06]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by tanto259** [comment] 2016-07-11 11:54
Correct me if I wrong, but this looks like a duplicate of #736 if that is the case your issue should be fixed already. Just wait for a new update to be released.

**Comment by WildBamaBoy** [comment] 2016-07-13 18:47
#736

**Closed by WildBamaBoy** 2016-07-13 18:47 UTC

**Comment by L3DWORKS** [comment] 2016-07-28 01:12
This issue is still pressent in the 1,9 version... same thing has just happened to me! :(

`Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at mca.entity.EntityChoreFishHook.REPLACED_onUpdate(EntityChoreFishHook.java:193)
	at mca.entity.EntityChoreFishHook.func_70071_h_(EntityChoreFishHook.java)
	at net.minecraft.world.World.func_72866_a(World.java:1934)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:836)
	at net.minecraft.world.World.func_72870_g(World.java:1903)
	at net.minecraft.world.World.func_72939_s(World.java:1737)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:705)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:609)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:239)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:467)
	at java.lang.Thread.run(Thread.java:745)`
