### ISSUE TITLE
Invisible Villagers (fix: use Forge 2491)

### ISSUE THREAD

**Issue by Elfykins** [WildBamaBoy/minecraft-comes-alive#917] opened 2017-11-13 05:02 UTC
When I first started MCA in my game my villagers were showing up perfectly fine, but when I left the village to go exploring and came back later they were all invisible. Even though they are there as you can hear them moving about etc, they are completely invisible and I cannot interact with them.

The only mods I have installed are the ones required for MCA and of course, MCA.

Using latest version of this, and Minecraft Version 1.12.2

Forge Version: 14.23.0.2540
RadixCore: -Latest downloaded via your website

**Comment by Elfykins** [comment] 2017-11-13 05:11
I am also unable to access the Config Menu inside of my game while playing, but can from main menu.

**Comment by Elfykins** [comment] 2017-11-13 05:33
Seems forge version 14.23.0.2538 + does not like MCA and causes villagers the vanish.

Going back to version 14.23.0.2537 of Forge fixes the issue and brings back my villagers.

**Comment by Galindorf** [comment] 2017-11-13 06:32
if you are looking for the in game config menu, I don't think there is one. 
You can change configs the old fashioned way! If you haven't before, go to 
..Minecraft folder (where the mods folder is located). In there is a folder 
called "config." In THAT folder, is a file named mca.cfg. Before I change 
anything, I make a copy and rename it mca-original.cfg so I can go back to 
default if I mess something up. Open the file in a basic text editor like 
Notepad (windows) or TextEdit(Mac) and make your changes. Hit save! Most of 
the things are pretty self explanatory.

**Comment by Elfykins** [comment] 2017-11-13 19:45
There was a in game config, it was under the main menu, you just cannot access it while actually PLAYING the game.

**Comment by PurpleHel** [comment] 2017-11-14 13:32
Not being able to access the config while in the game isn't unheard of. Mods that make significant changes that don't reload in game well often have it set up that way.

Thanks for the info on forge, I was wondering where my villagers went, but my world doesn't actually load without all my mods, which makes trying to troubleshoot difficult!

**Comment by WildBamaBoy** [comment] 2017-11-15 15:48
Confirmed Forge 2538+ causes this problem to appear. Fix for now is to use the recommended version for 1.12.2.

**Comment by BuilderDan** [comment] 2017-11-15 20:07
Not really a fix, the real fix is to just not use your mod at all.

**Comment by WildBamaBoy** [comment] 2017-11-15 20:41
Golly gee, that was clever. 10/10

The issue was renamed for those that come across this problem to have a quick fix. The issue remains open because I intend to look into the problem and provide a true fix.

EDIT: Seems he removed his post. ¯\_(ツ)_/¯

**Comment by maxanier** [comment] 2017-11-16 13:31
This issue is a bug in Forge (https://github.com/MinecraftForge/MinecraftForge/issues/4523) and should be fixed in Forge 2543+ (https://github.com/MinecraftForge/MinecraftForge/pull/4524)

**Comment by BuilderDan** [comment] 2017-11-16 18:52
I was just being blunt @WildBamaBoy its easier to just not use the mod until there's a fix. But I understand why you said the contrary.

**Comment by WildBamaBoy** [comment] 2017-11-16 21:07
Excellent, thank you for notifying me @maxanier

**Comment by Enverex** [comment] 2017-11-18 17:28
Negative, still doesn't work in Forge 2545.

```
[17:26:40] [main/FATAL]: Unreported exception thrown!
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
	at mca.entity.VillagerAttributes.getProfessionEnum(VillagerAttributes.java:215) ~[VillagerAttributes.class:?]
	at mca.entity.EntityVillagerMCA.func_184586_b(EntityVillagerMCA.java:678) ~[EntityVillagerMCA.class:?]
	at mca.entity.EntityVillagerMCA.func_184582_a(EntityVillagerMCA.java:800) ~[EntityVillagerMCA.class:?]
	at net.minecraft.entity.EntityLivingBase.func_184614_ca(EntityLivingBase.java:1608) ~[vp.class:?]
	at DynamicLights.getLightLevel(DynamicLights.java:336) ~[DynamicLights.class:?]
	at DynamicLights.updateMapDynamicLights(DynamicLights.java:121) ~[DynamicLights.class:?]
	at DynamicLights.update(DynamicLights.java:95) ~[DynamicLights.class:?]
	at net.minecraft.client.renderer.RenderGlobal.func_174970_a(RenderGlobal.java:1170) ~[buy.class:?]
	at com.cjm721.overloaded.client.render.RenderGlobalSpectator.func_174970_a(RenderGlobalSpectator.java:20) ~[RenderGlobalSpectator.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1716) ~[buq.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1606) ~[buq.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1377) ~[buq.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_152]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_152]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_152]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_152]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
```

**Comment by WildBamaBoy** [comment] 2017-11-18 19:30
@Enverex That's a different issue, #912

**Comment by Enverex** [comment] 2017-11-18 19:40
Sorry, had two issues open at the same time and posted in the wrong one!

**Comment by Galindorf** [comment] 2017-11-21 00:11
Here's a piece of info, not sure if it's related. I'm using Forge 2491. I saved a zombie villager, and when he finally stopped shaking and became a person, he was invisible! None of the rest of my villagers are invisible. (man, tough life, went from being a zombie to being the Invisible Man... what's next, werewolf??)

**Comment by WildBamaBoy** [comment] 2017-11-21 00:53
This might be related to a different problem - are you able to provide the game's console output from when this occurred?

**Comment by Galindorf** [comment] 2017-11-21 03:09
ah, this happened a couple of days ago (he's already gotten married and had a baby! He must be really charming?)

I'm going to do a fresh one and see what happens, and paste the console output here.

**Comment by Galindorf** [comment] 2017-11-21 03:22
OK, freshly spawned zombie villager, creative mode, potion+apple. Interestingly, I got the same guy as I did last time, Steve the Farmer, who is invisible. Console post:  https://pastebin.com/rvzkDBPP

(hopefully I did that right, never used PasteBin before)

**Comment by WildBamaBoy** [comment] 2017-11-21 03:33
Indeed this is a different issue unrelated to the Forge version. Will fix. 👍

**Comment by Galindorf** [comment] 2017-11-21 03:37
cool. FYI attempting to use the Villager Editor to GIVE them a new texture results in a crash. But you probably already know.

**Comment by PurpleHel** [comment] 2017-11-21 06:45
Yeah, I saw that too. Also was always steve the farmer.

**Comment by JEGomorph** [comment] 2017-11-22 13:36
Oops forget that stuff about using a different java. The actual cause of the rendering error (invisible or purple/black) is leaving other versions of MCA in your mods folder. Even though Minecraft is suppose to not load other mod versions if they're in their MC version named folder, parameters from those other versions do seem to be loaded & fudging stuff up. The simplest workaround is only have the 1.12.2 folder in your mods folder when running Minecraft 1.12.2, so drag&drop the other ones somewhere else temporarily. Or you can just take out any MCA jars in the other version folders likewise temporarily. Other Radixcore jars don't affect the loaded game so you can leave them where they are.

**Comment by JEGomorph** [comment] 2017-11-22 14:21
& yeah the Villager Editor crash is caused by a sequential break in the skin numbering. It always crashes if you attempt to scroll the left **<<** to view textures backwards from "_farmerm25_". The system is  expecting a "_farmerm24_" but however there is no such file. This also prevents viewing "_farmerm25_" if scrolling the right **>>** to browse forward. It instead goes back to "_farmerm1_" after "_farmerm23_". Unfortunately renaming "_farmerm25_" to "_farmerm24_" causes scrolling left **<<** to stop at _m24_ when viewing farmerm textures. Renaming to "_farmerm0_" causes scrolling right **>>** to then stop working for farmerm completely. You just can't win : P. Viewing the farmerm textures with a rename at least doesn't crash the game though. Odd that in MC 1.10.2, this is not an issue. It's UI protocol seems to be more logical or robust than in 1.12.2.

**Comment by CritFlaw** [comment] 2018-03-11 03:57
I'm not sure what the update with this issue is but I just did a test with just mca & radix installed and having the same issue when curing the villagers. Has there been a fix?

**Comment by Accord2** [comment] 2018-06-10 21:34
I am playing with forge 2491 and the villagers are still invisible.

**Comment by Lilen77** [comment] 2018-07-06 15:03
As of 7/6/18 and forge 2729 this is still an issue. 
I understand modding is difficult but this has been 8 months.

**Comment by PDelta41** [comment] 2018-12-08 01:41
This issue persists as of 12/07/2018 & Forge 2784.

**Comment by alphawolf918** [comment] 2019-01-28 01:34
I also am having this issue with the latest mod and Forge (recommended) versions.

**Comment by CritFlaw** [comment] 2019-01-28 01:52
I think at this point we can assume this mod is abandoned by the dev.

**Closed as completed** 2019-06-02 02:57 UTC
Labels: bug, 1.12.2
