### ISSUE TITLE
Client crash with dedicated server - Procreation (for real)

### ISSUE THREAD

**Issue by MxtressMyxx** [WildBamaBoy/minecraft-comes-alive#952] opened 2018-01-04 15:24 UTC
Exploring a newly generated world, client crashes when chunks load villagers that appear to be... ahem, procreating. Logs to follow.

**Comment by MxtressMyxx** [comment] 2018-01-04 15:26
https://gist.github.com/AnsuzThurisaz/4d49f4b6d0398d59214e2213d1746e26

**Comment by MxtressMyxx** [comment] 2018-01-04 15:28
https://gist.github.com/AnsuzThurisaz/13f4490679e81619f069d25b69af9ee1

**Comment by VirtualGaming1** [comment] 2018-01-08 11:02
Duplicate of #884

**Closed as completed** 2018-01-28 08:26 UTC
