### ISSUE TITLE
Duplicating villagers when supplied with a villager bed

### ISSUE THREAD

**Issue by RealGrep** [WildBamaBoy/minecraft-comes-alive#641] opened 2016-02-20 17:53 UTC
I've had villagers duplicating. Not sure exactly when it happens, but it only started when I supplied a villager bed. I had two beds, a wife and child, in the same room. No other villagers anywhere nearby. I came back and had two wives. Later, four. A guard spawned, and later I had two of the same guard.

The inventory was also duplicated, and the name and everything else was identical. I took away the beds and I, erm, murdered the dopplegangers (I'm a monster!) and I have had no more duplications. Fairly sure it's the beds that are causing it, somehow. Haven't really seen anything in the logs that might help.

Minecraft 1.8.9, Forge 1755, MCA version 5.1.1.2. Let me know if you need more information, testing, etc. Thanks!

**Comment by WildBamaBoy** [comment] 2016-03-10 23:30
Did this happen on single player, or a server?

**Comment by WildBamaBoy** [comment] 2016-03-19 22:40
Unable to reproduce, closing as no information provided

**Closed by WildBamaBoy** 2016-03-19 22:40 UTC
Labels: 1.8.9, bug, need information
