### ISSUE TITLE
Trading with NPCs crash

### ISSUE THREAD

**Issue by AwlsomeAlex** [WildBamaBoy/minecraft-comes-alive#271] opened 2015-03-25 00:38 UTC
Hello, everytime I try to trade with a NPC, Minecraft keeps crashing. I tried it multiple times and it still happens.

MC Version: 1.7.10
---------------------------------------------------------------------
Forge: Current (Latest) 1.7.10 [From your website]
---------------------------------------------------------------------
MCA Version: 5.0.0 BETA
---------------------------------------------------------------------
All Mods:
1.) MCA-1.7.10-5.0.0-beta-universal.jar
2.) Optifine_1.7.10_HD_U_B5.jar
3.) RadixCore-1.7.10-2.0.0-universal.jar
---------------------------------------------------------------------
Crash Report:
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 3/24/15 8:32 PM
Description: Ticking memory connection

java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
	at mca.entity.EntityHuman.func_70933_a(EntityHuman.java:1050)
	at net.minecraft.inventory.SlotMerchantResult.func_82870_a(SourceFile:58)
	at net.minecraft.inventory.Container.func_75144_a(SourceFile:238)
	at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:883)
	at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:32)
	at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:10)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at mca.entity.EntityHuman.func_70933_a(EntityHuman.java:1050)
	at net.minecraft.inventory.SlotMerchantResult.func_82870_a(SourceFile:58)
	at net.minecraft.inventory.Container.func_75144_a(SourceFile:238)
	at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:883)
	at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:32)
	at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:10)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@1399de5f
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_40, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 836645872 bytes (797 MB) / 1363673088 bytes (1300 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 Optifine OptiFine_1.7.10_HD_U_B5 5 mods loaded, 5 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.85.1291} [Forge Mod Loader] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.2.1291} [Minecraft Forge] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	RadixCore{2.0.0} [RadixCore] (RadixCore-1.7.10-2.0.0-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MCA{5.0.0-beta} [Minecraft Comes Alive] (MCA-1.7.10-5.0.0-beta-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['Awlsomeabc1'/276, l='MCA Survival', x=-248.14, y=79.00, z=238.57]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by WildBamaBoy** [comment] 2015-03-25 00:50
Dupe of #256, will be repaired in next update.

**Closed by WildBamaBoy** 2015-03-25 00:50 UTC
