### ISSUE TITLE
MCA generates bottomless flowers making Waila to crash the game

### ISSUE THREAD

**Issue by zuoanqh** [WildBamaBoy/minecraft-comes-alive#683] opened 2016-04-17 12:39 UTC
Hi, while this is partly problem of Waila, MCA appears to be generating invalid flowers which you might want to fix. This happens sometimes when I chose "I live in a village" when using the crystal orb thingy. Here's a screenshot: (looking at the peony on the right caused the crash below)

![2016-04-17_21 30 42](https://cloud.githubusercontent.com/assets/8357370/14586971/d3ae8492-04e3-11e6-8048-469676c9e27b.png)

World download: 
[New World.zip](https://github.com/WildBamaBoy/minecraft-comes-alive/files/222634/New.World.zip)

Environment is Forge 1865, MCA 5.1.2, RadixCore 2.1.0, Waila 1.7.0-B2. (only those)

Crash report: 
```
---- Minecraft Crash Report ----
// Why did you do that?

Time: 4/17/16 9:30 PM
Description: Unexpected error

java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=half, clazz=class net.minecraft.block.BlockDoublePlant$EnumBlockHalf, values=[upper, lower]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:192)
	at net.minecraft.block.BlockDoublePlant.func_176201_c(BlockDoublePlant.java:268)
	at mcp.mobius.waila.addons.vanillamc.HUDHandlerVanilla.getWailaStack(HUDHandlerVanilla.java:81)
	at mcp.mobius.waila.overlay.RayTracing.getIdentifierItems(RayTracing.java:153)
	at mcp.mobius.waila.overlay.RayTracing.getIdentifierStack(RayTracing.java:96)
	at mcp.mobius.waila.overlay.RayTracing.getTargetStack(RayTracing.java:65)
	at mcp.mobius.waila.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:77)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_29_WailaTickHandler_tickClient_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:336)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1845)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:366)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:192)
	at net.minecraft.block.BlockDoublePlant.func_176201_c(BlockDoublePlant.java:268)
	at mcp.mobius.waila.addons.vanillamc.HUDHandlerVanilla.getWailaStack(HUDHandlerVanilla.java:81)
	at mcp.mobius.waila.overlay.RayTracing.getIdentifierItems(RayTracing.java:153)
	at mcp.mobius.waila.overlay.RayTracing.getIdentifierStack(RayTracing.java:96)
	at mcp.mobius.waila.overlay.RayTracing.getTargetStack(RayTracing.java:65)
	at mcp.mobius.waila.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:77)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_29_WailaTickHandler_tickClient_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:336)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['zuoanqh'/354, l='MpServer', x=-77.86, y=107.00, z=194.98]]
	Chunk stats: MultiplayerChunkCache: 569, 569
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-24,64,192), Chunk: (at 8,4,0 in -2,12; contains blocks -32,0,192 to -17,255,207), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 951 game time, 951 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 131 total; [EntityBat['Bat'/8193, l='MpServer', x=-142.19, y=19.35, z=225.98], EntityCreeper['Creeper'/6235, l='MpServer', x=-69.50, y=33.00, z=209.50], EntityBat['Bat'/8288, l='MpServer', x=-52.78, y=42.62, z=139.25], EntitySpider['Spider'/6249, l='MpServer', x=-98.50, y=41.00, z=263.50], EntitySkeleton['Skeleton'/6251, l='MpServer', x=-154.50, y=51.00, z=222.50], EntityChicken['Chicken'/118, l='MpServer', x=-153.38, y=72.00, z=224.60], EntityChicken['Chicken'/119, l='MpServer', x=-150.20, y=71.00, z=226.47], EntityChicken['Chicken'/120, l='MpServer', x=-147.89, y=71.00, z=237.09], EntityChicken['Chicken'/121, l='MpServer', x=-155.50, y=72.00, z=225.50], EntityCow['Cow'/122, l='MpServer', x=-128.50, y=70.00, z=241.50], EntityCow['Cow'/123, l='MpServer', x=-129.50, y=70.00, z=242.50], EntityCow['Cow'/124, l='MpServer', x=-129.50, y=70.00, z=245.50], EntityCow['Cow'/125, l='MpServer', x=-132.50, y=71.00, z=247.50], EntityCow['Cow'/130, l='MpServer', x=-108.50, y=92.00, z=198.50], EntityCow['Cow'/131, l='MpServer', x=-98.95, y=98.00, z=203.48], EntityCow['Cow'/132, l='MpServer', x=-106.81, y=94.00, z=199.44], EntityCow['Cow'/133, l='MpServer', x=-110.50, y=89.00, z=198.50], EntityCow['Cow'/134, l='MpServer', x=-105.43, y=95.00, z=207.72], EntityCow['Cow'/135, l='MpServer', x=-99.86, y=97.00, z=206.78], EntityCow['Cow'/136, l='MpServer', x=-105.44, y=95.00, z=208.78], EntityCow['Cow'/137, l='MpServer', x=-104.54, y=95.00, z=207.45], EntityCow['Cow'/138, l='MpServer', x=-97.50, y=65.00, z=131.50], EntityCow['Cow'/139, l='MpServer', x=-95.50, y=69.00, z=129.50], EntityCow['Cow'/140, l='MpServer', x=-93.50, y=72.00, z=128.50], EntityCow['Cow'/141, l='MpServer', x=-94.50, y=69.00, z=129.50], EntitySheep['Sheep'/142, l='MpServer', x=-96.50, y=80.00, z=122.50], EntitySheep['Sheep'/143, l='MpServer', x=-94.50, y=88.00, z=120.50], EntitySheep['Sheep'/144, l='MpServer', x=-93.50, y=80.00, z=121.50], EntitySheep['Sheep'/145, l='MpServer', x=-95.50, y=80.00, z=122.50], EntityCow['Cow'/155, l='MpServer', x=-79.50, y=96.00, z=228.50], EntityCow['Cow'/156, l='MpServer', x=-88.18, y=95.00, z=231.50], EntityCow['Cow'/157, l='MpServer', x=-77.78, y=97.00, z=231.70], EntityCow['Cow'/160, l='MpServer', x=-51.90, y=62.55, z=174.56], EntityCow['Cow'/161, l='MpServer', x=-56.50, y=63.00, z=176.56], EntityCow['Cow'/162, l='MpServer', x=-57.48, y=66.00, z=179.20], EntityCow['Cow'/163, l='MpServer', x=-58.50, y=67.00, z=177.50], EntityCow['Cow'/165, l='MpServer', x=-69.40, y=85.00, z=275.53], EntityCow['Cow'/166, l='MpServer', x=-70.53, y=85.00, z=275.04], EntityCow['Cow'/167, l='MpServer', x=-69.40, y=85.00, z=274.43], EntitySheep['Sheep'/168, l='MpServer', x=-71.50, y=85.00, z=271.50], EntitySkeleton['Skeleton'/2216, l='MpServer', x=-78.50, y=51.00, z=117.50], EntitySheep['Sheep'/169, l='MpServer', x=-63.77, y=85.00, z=271.52], EntitySheep['Sheep'/170, l='MpServer', x=-68.50, y=86.00, z=270.50], EntitySheep['Sheep'/171, l='MpServer', x=-67.36, y=86.00, z=270.88], EntityChicken['Chicken'/201, l='MpServer', x=-2.57, y=63.00, z=120.23], EntityCreeper['Creeper'/8419, l='MpServer', x=-27.50, y=19.00, z=142.50], EntitySquid['Squid'/2340, l='MpServer', x=-134.76, y=62.28, z=156.60], EntitySkeleton['Skeleton'/8505, l='MpServer', x=-25.50, y=14.00, z=168.50], EntityEnderman['Enderman'/8529, l='MpServer', x=-9.50, y=13.00, z=227.50], EntitySquid['Squid'/2390, l='MpServer', x=-139.61, y=61.60, z=155.03], EntityPlayerSP['zuoanqh'/354, l='MpServer', x=-77.86, y=107.00, z=194.98], EntityZombie['Zombie'/6538, l='MpServer', x=-14.50, y=11.00, z=169.50], EntityBat['Bat'/6585, l='MpServer', x=-21.39, y=48.03, z=196.54], EntityBat['Bat'/6672, l='MpServer', x=-10.93, y=19.07, z=216.15], EntityZombie['Zombie'/6677, l='MpServer', x=-24.50, y=16.00, z=178.50], EntityZombie['Zombie'/571, l='MpServer', x=-0.50, y=23.00, z=169.50], EntityBat['Bat'/6728, l='MpServer', x=-9.25, y=13.10, z=199.75], EntityCreeper['Creeper'/2646, l='MpServer', x=-82.50, y=46.00, z=131.50], EntityCreeper['Creeper'/2682, l='MpServer', x=-120.50, y=73.00, z=122.50], EntityCreeper['Creeper'/6781, l='MpServer', x=-153.50, y=57.00, z=212.50], EntityCreeper['Creeper'/6818, l='MpServer', x=-9.50, y=13.00, z=222.50], EntityBat['Bat'/2723, l='MpServer', x=-18.59, y=48.46, z=197.15], EntitySkeleton['Skeleton'/2767, l='MpServer', x=-49.77, y=22.00, z=203.50], EntityBat['Bat'/8925, l='MpServer', x=-107.63, y=43.81, z=126.65], EntityCreeper['Creeper'/8960, l='MpServer', x=-25.50, y=19.00, z=142.50], EntityBat['Bat'/8984, l='MpServer', x=-54.22, y=41.99, z=138.52], EntityBat['Bat'/9008, l='MpServer', x=-128.17, y=29.15, z=126.69], EntitySkeleton['Skeleton'/9029, l='MpServer', x=-33.50, y=79.00, z=230.50], EntitySquid['Squid'/861, l='MpServer', x=-82.59, y=61.82, z=148.62], EntityCreeper['Creeper'/7006, l='MpServer', x=-62.50, y=41.00, z=137.50], EntityZombie['Zombie'/9062, l='MpServer', x=-31.50, y=18.00, z=224.50], EntityBat['Bat'/9064, l='MpServer', x=-32.69, y=15.00, z=158.30], EntityZombie['Zombie'/7048, l='MpServer', x=-4.50, y=19.00, z=207.50], EntityCreeper['Creeper'/7049, l='MpServer', x=-100.50, y=42.00, z=121.50], EntityZombie['Zombie'/7125, l='MpServer', x=-50.50, y=31.00, z=228.50], EntityZombie['Zombie'/9214, l='MpServer', x=-9.50, y=14.00, z=219.50], EntityZombie['Zombie'/7180, l='MpServer', x=-42.50, y=51.00, z=146.50], EntityCreeper['Creeper'/7182, l='MpServer', x=-75.50, y=51.00, z=227.50], EntitySkeleton['Skeleton'/9253, l='MpServer', x=-117.50, y=42.00, z=129.50], EntityWitch['Witch'/3183, l='MpServer', x=-24.50, y=13.00, z=212.50], EntityCreeper['Creeper'/7280, l='MpServer', x=-100.50, y=37.00, z=270.50], EntityCreeper['Creeper'/3184, l='MpServer', x=-73.50, y=45.00, z=126.50], EntityCreeper['Creeper'/7308, l='MpServer', x=-74.50, y=51.00, z=223.50], EntityZombie['Zombie'/7327, l='MpServer', x=-147.50, y=34.00, z=180.50], EntityCreeper['Creeper'/7497, l='MpServer', x=-26.50, y=15.00, z=172.50], EntityEnderman['Enderman'/1368, l='MpServer', x=-89.50, y=46.00, z=125.50], EntityZombie['Zombie'/3442, l='MpServer', x=-31.50, y=46.00, z=261.50], EntitySkeleton['Skeleton'/3449, l='MpServer', x=0.50, y=22.00, z=228.50], EntitySquid['Squid'/1407, l='MpServer', x=-141.20, y=61.81, z=156.60], EntitySkeleton['Skeleton'/5572, l='MpServer', x=-119.50, y=73.00, z=122.50], EntityZombie['Zombie'/3533, l='MpServer', x=-39.50, y=17.00, z=204.50], EntityZombie['Zombie'/7684, l='MpServer', x=-81.30, y=44.07, z=128.70], EntityCreeper['Creeper'/3654, l='MpServer', x=-0.50, y=19.00, z=178.50], EntityCreeper['Creeper'/5715, l='MpServer', x=-28.50, y=44.00, z=222.50], EntityCreeper['Creeper'/7785, l='MpServer', x=-67.50, y=33.00, z=211.50], EntityWitch['Witch'/7821, l='MpServer', x=-0.50, y=19.00, z=170.50], EntityZombie['Zombie'/7825, l='MpServer', x=-13.50, y=12.00, z=171.50], EntityCreeper['Creeper'/3735, l='MpServer', x=-22.50, y=21.00, z=153.50], EntitySkeleton['Skeleton'/1709, l='MpServer', x=-104.50, y=42.00, z=130.50], EntityEnderman['Enderman'/7866, l='MpServer', x=-24.50, y=13.00, z=213.50], EntitySkeleton['Skeleton'/7930, l='MpServer', x=-37.50, y=48.00, z=173.50], EntityBat['Bat'/1790, l='MpServer', x=-43.67, y=20.10, z=202.63], EntityCreeper['Creeper'/7937, l='MpServer', x=-36.50, y=48.00, z=171.50], EntityCreeper['Creeper'/3845, l='MpServer', x=-1.50, y=20.00, z=221.50], EntityCreeper['Creeper'/5898, l='MpServer', x=-60.50, y=27.00, z=202.50], EntityCreeper['Creeper'/7946, l='MpServer', x=-27.50, y=20.00, z=152.50], EntitySkeleton['Skeleton'/5907, l='MpServer', x=-86.50, y=48.00, z=119.50], EntityZombie['Zombie'/5958, l='MpServer', x=-120.50, y=71.00, z=216.50], EntityCreeper['Creeper'/5982, l='MpServer', x=-35.50, y=18.00, z=207.50], EntityCreeper['Creeper'/8038, l='MpServer', x=-92.50, y=39.00, z=139.50], EntityZombie['Zombie'/3944, l='MpServer', x=-34.50, y=18.00, z=215.50], EntityBat['Bat'/1915, l='MpServer', x=-43.84, y=46.31, z=174.25], EntityZombie['Zombie'/8068, l='MpServer', x=-42.50, y=45.00, z=175.50], EntityItem['item.item.seeds'/8075, l='MpServer', x=-79.95, y=107.00, z=225.98], EntityHuman['Dolly'/8081, l='MpServer', x=-38.73, y=107.00, z=205.39], EntityHuman['Eliot'/8084, l='MpServer', x=-52.42, y=107.00, z=196.47], EntityHuman['Rayne'/8086, l='MpServer', x=-53.40, y=107.00, z=205.44], EntityHuman['Phil'/8087, l='MpServer', x=-46.00, y=107.00, z=211.00], EntityHuman['Ebony'/8089, l='MpServer', x=-51.00, y=107.00, z=225.00], EntityHuman['Naya'/8093, l='MpServer', x=-46.41, y=107.00, z=226.51], EntityHuman['Dario'/8094, l='MpServer', x=-45.26, y=107.00, z=226.57], EntityHuman['Taylor'/8095, l='MpServer', x=-49.46, y=107.00, z=216.50], EntityZombie['Zombie'/8135, l='MpServer', x=-29.50, y=43.00, z=214.50], EntityItem['item.tile.doublePlant.paeonia'/8139, l='MpServer', x=-14.83, y=67.00, z=158.14], EntityHuman['Callie'/8141, l='MpServer', x=-44.56, y=107.00, z=188.52], EntityHuman['Dina'/8142, l='MpServer', x=-44.33, y=107.00, z=235.52], EntityHuman['Delina'/8143, l='MpServer', x=-55.70, y=107.00, z=206.70], EntityCreeper['Creeper'/6097, l='MpServer', x=-13.50, y=20.00, z=155.50], EntityItem['item.item.leather'/8147, l='MpServer', x=-69.55, y=107.00, z=219.51], EntityItem['item.item.beefRaw'/8148, l='MpServer', x=-69.54, y=107.00, z=215.91], EntityBat['Bat'/4090, l='MpServer', x=-28.80, y=12.58, z=165.95]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:409)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2647)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:395)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.9
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1295223768 bytes (1235 MB) / 1821900800 bytes (1737 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.23 Powered by Forge 12.16.0.1865 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.9-12.16.0.1865-1.9.jar) 
	UCHIJAAAA	Forge{12.16.0.1865} [Minecraft Forge] (forge-1.9-12.16.0.1865-1.9.jar) 
	UCHIJAAAA	RadixCore{1.9-2.1.0} [RadixCore] (RadixCore-1.9-2.1.0-BETA-universal.jar) 
	UCHIJAAAA	MCA{1.9-5.1.2} [Minecraft Comes Alive] (MCA-1.9-5.1.2-BETA-universal.jar) 
	UCHIJAAAA	Waila{1.7.0} [Waila] (Waila-1.7.0-B2_1.9.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 354.35' Renderer: 'GeForce GT 755M/PCIe/SSE2'
	Launched Version: forge-12.16.0.1865
	LWJGL: 2.9.4
	OpenGL: GeForce GT 755M/PCIe/SSE2 GL version 4.5.0 NVIDIA 354.35, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz
```

**Comment by mezzodrinker** [comment] 2016-04-17 15:01
MCA doesn't do any kind of world generation, actually.

**Comment by WildBamaBoy** [comment] 2016-04-17 15:35
The above is correct.

**Comment by mezzodrinker** [comment] 2016-04-17 15:38
Damn. Sorry. I didn't read through the text carefully. It's about the destiny options.

**Comment by zuoanqh** [comment] 2016-04-17 16:55
Umm so this got closed wrongly, do i make another an issue? or you're going re-open it?

**Comment by kotoroshinoto** [comment] 2016-04-22 02:04
can confirm this is happening. Seems limited to peony in my experience so far. It is specifically from the town spawed by the destiny choices.

**Comment by WildBamaBoy** [comment] 2016-07-05 22:39
Found the issue, caused by improper removal of `double_plant` in the schematic spawner.

**Comment by WildBamaBoy** [comment] 2016-07-05 22:51
Fixed in next update

**Closed by WildBamaBoy** 2016-07-05 22:51 UTC
Labels: 1.8.9, 1.9, crash
