### ISSUE TITLE
Shift clicking into a full villager inventory crashes game

### ISSUE THREAD

**Issue by GameRKade** [WildBamaBoy/minecraft-comes-alive#979] opened 2018-02-23 01:09 UTC
The title pretty much describes it all, if you shift click an item into a villager's inventory when it's full, the game completely crashes.

I am running MCA 5.3.1
I am running Forge 14.23.0.2491
Easily able to be replicated: just fill a villager's inventory then shift click any item

The crash report button doesn't seem to do anything, but this popped up in "Show more details"

The game crashed whilst updating screen events
The game crashed whilst updating screen events
Error: java.lang.NullPointerException: Updating screen events

**Comment by SDPhantom** [comment] 2018-03-11 09:25
Same issue causes NPE in GUI renderer.

Minecraft 1.12.2
Forge 14.23.2.2624
MCA 5.3.1
RadixCore 2.2.1

https://gist.github.com/SDPhantom/b740d133663249c56ac3269a16f52ae7

**Comment by SDPhantom** [comment] 2018-03-13 23:49
Looks like this is a duplicate of #953

**Closed as completed** 2019-06-02 02:57 UTC
