### ISSUE TITLE
Engaged, But Can't Marry?

### ISSUE THREAD

**Issue by JustStrange** [WildBamaBoy/minecraft-comes-alive#908] opened 2017-11-04 05:28 UTC
Sooo, I am playing 1.12x-5.3.1 MCA with Forge 1.12 and I encountered a problem I can't solve.

I started the game and after a while, I tried to marry a villager. At first, it said I was already married, but I hadn't married anyone. So I fixed it using a priest, and engaging with the NPC had worked! 
Now the problem is: I can't marry. Everytime I try gifting the NPC with a wedding ring, it says that the NPC is already married, but is engaged to me??

I have yet to find a solution to this problem, so please help!

**Comment by WildBamaBoy** [comment] 2017-11-15 15:54
Unable to reproduce this on Forge 2491. Will continue testing additional Forge versions to see if this can be reproduced as later versions of Forge seem to be causing an invisible villager issue.

Unless you're able to provide the exact Forge version you were using?

**Comment by C0rn3j** [comment] 2017-11-18 13:57
This is a duplicate of https://github.com/WildBamaBoy/minecraft-comes-alive/issues/902

**Comment by SDPhantom** [comment] 2017-12-18 07:40
I'm getting the issue on Forge 2562. It only seems to affect SMP. Singleplayer works fine.

**Closed as completed** 2019-06-02 02:58 UTC
Labels: bug, 1.12.2
