### ISSUE TITLE
1.7.10 Unable to set home

### ISSUE THREAD

**Issue by TreePuncher9501** [WildBamaBoy/minecraft-comes-alive#302] opened 2015-04-08 23:39 UTC
With my small family, I am unable to set home. If one needs any information additionally, ask. The family is 1 wife and 3 children, and no matter what I do I cannot get them to set home.

**Comment by rain77** [comment] 2015-04-09 00:08
What happens when you try to set the home? Do you get no message at all? Do you get an error log?

If you get a message among the lines of "This is not a safe place for me" then try moving the NPC away from walls.

**Comment by TreePuncher9501** [comment] 2015-04-09 02:38
I do get that message, but what confuses me is this: I try to set their homes in my own, dead center. 10 blocks any which way, and the ceiling a good 10-12 up, whereas if I try to, for example, set it in a 3 wide alleyway it somehow works. That's where my confusion lies.

**Comment by WildBamaBoy** [comment] 2015-04-09 02:47
What version of MCA are you using?

**Comment by TreePuncher9501** [comment] 2015-04-09 02:49
Version 5.0.0, designed for minecraft version 1.7.10.

**Comment by WildBamaBoy** [comment] 2015-04-09 02:58
Alright, when you set their home, make sure that they are not close to any half blocks, torches, or any other "block" that you can usually walk through. If possible, could you take a screenshot of the area they are standing in when you attempt to set their home?

**Comment by TreePuncher9501** [comment] 2015-04-09 03:00
I will take a screenshot tomorrow, as it's 11:00 where I'm at currently and communicating via phone. I will check for torches or the like then as well, and will inform you on whether or not it works.

**Comment by WildBamaBoy** [comment] 2015-04-09 03:02
No problem, post it whenever you get the chance.

**Comment by TreePuncher9501** [comment] 2015-04-09 20:24
Alright, here. The house isn't as big as I predicted from the phone, but it's still much bigger and wider than the alleyway. The village is custom-built with chisel-mod blocks. The house has no modded blocks inside aside from the windows which function as glowstone and the beds, which are from MCA of course. I have a few mods, but none of these should cause issues.

Images: 
![2015-04-09_16 17 23](https://cloud.githubusercontent.com/assets/10838395/7076063/be918176-ded4-11e4-8d82-12287b2a3aa9.png)
The house

![2015-04-09_16 17 36](https://cloud.githubusercontent.com/assets/10838395/7076068/caab9096-ded4-11e4-9842-6283e2320b65.png)
The diamond blocks are there to show where I'm trying to set their homes.

![2015-04-09_16 19 05](https://cloud.githubusercontent.com/assets/10838395/7076074/d9e0a754-ded4-11e4-8957-7b7ce606aa4b.png)
The whole village

**Comment by SNDGIRL** [comment] 2015-04-10 04:17
Hmm maybe something was creating an error? But it's good that you got it fixed

**Comment by moinecraftperv** [comment] 2015-04-10 06:05
Did you use slabs for the floor

**Comment by TreePuncher9501** [comment] 2015-04-10 10:37
No, the floor is all planks. Solid blocks, not slabs.

**Comment by moinecraftperv** [comment] 2015-04-10 14:30
Maybe because there is no nearby walls the villager thinks you set her home outside which is unsafe?

**Comment by SNDGIRL** [comment] 2015-04-10 16:59
I think it's a glitch it happens quite a bit

**Comment by Time6628** [comment] 2015-04-11 10:23
Maybe it's because they think the area around it isn't light properly.

**Comment by TreePuncher9501** [comment] 2015-04-11 11:02
The windows provide a glowstone-esq light level throughout the house, so that can't be the issue.

**Comment by Time6628** [comment] 2015-04-11 12:30
Place some torches around the spot you are trying to set the home at. I think the NPC isn't regonizing the light sources so it thinks the room is unsafe. Just a theroy lol.

**Comment by SNDGIRL** [comment] 2015-04-11 23:47
I think Time's is a good theory, or try setting their home somewhere else

**Comment by WildBamaBoy** [comment] 2015-04-12 05:30
Light levels do not affect whether or not a home point is valid, only the blocks nearby do.

I can't seem to reproduce this with the same sort of setup. Can you put your world up for download @TreePuncher9501?

**Comment by WildBamaBoy** [comment] 2015-04-25 05:27
Issue should be addressed in 5.0.2 via this commit: https://github.com/WildBamaBoy/minecraft-comes-alive/commit/74bdf60e9618d1fa8b279ffa51fb00678631be7c

**Closed by WildBamaBoy** 2015-04-25 05:27 UTC
Labels: functional
