### ISSUE TITLE
it keeps crashing, I cant log into world!

### ISSUE THREAD

**Issue by caitlincraft** [WildBamaBoy/minecraft-comes-alive#523] opened 2015-08-24 05:25 UTC
---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// I'm sorry, Dave.

Time: 8/23/15 10:19 PM
Description: Ticking entity

java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=part, clazz=class net.minecraft.block.BlockBed$EnumPartType, values=[head, foot]} as it does not exist in BlockState{block=minecraft:cobblestone, properties=[]}
	at net.minecraft.block.state.BlockState$StateImplementation.func_177229_b(BlockState.java:165)
	at mca.ai.AISleep.trySleepInBed(AISleep.java:354)
	at mca.ai.AISleep.onUpdateServer(AISleep.java:90)
	at mca.ai.AIManager.onUpdate(AIManager.java:45)
	at mca.entity.EntityHuman.func_70071_h_(EntityHuman.java:308)
	at net.minecraft.world.World.func_72866_a(World.java:1880)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:732)
	at net.minecraft.world.World.func_72870_g(World.java:1850)
	at net.minecraft.world.World.func_72939_s(World.java:1679)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:571)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:704)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:164)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.block.state.BlockState$StateImplementation.func_177229_b(BlockState.java:165)
	at mca.ai.AISleep.trySleepInBed(AISleep.java:354)
	at mca.ai.AISleep.onUpdateServer(AISleep.java:90)
	at mca.ai.AIManager.onUpdate(AIManager.java:45)
	at mca.entity.EntityHuman.func_70071_h_(EntityHuman.java:308)
	at net.minecraft.world.World.func_72866_a(World.java:1880)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:732)
	at net.minecraft.world.World.func_72870_g(World.java:1850)

-- Entity being ticked --
Details:
	Entity Type: MCA.EntityHuman (mca.entity.EntityHuman)
	Entity ID: 152
	Entity Name: Delina
	Entity's Exact location: 77.50, 65.00, 320.50
	Entity's Block location: 77.00,65.00,320.00 - World: (77,65,320), Chunk: (at 13,4,0 in 4,20; contains blocks 64,0,320 to 79,255,335), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Rider: ~~ERROR~~ NullPointerException: null
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1679)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:571)

-- Affected level --
Details:
	Level name: New World
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 625 Drop: 0
	Level seed: 2823504441536202647
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: 172.00,64.00,252.00 - World: (172,64,252), Chunk: (at 12,4,12 in 10,15; contains blocks 160,0,240 to 175,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 12544 game time, 12544 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 55966 (now: false), thunder time: 55572 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:704)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:164)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 122087016 bytes (116 MB) / 447029248 bytes (426 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 7, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.3.1504 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8-11.14.3.1504.jar) 
	UCHIJAAAA	Forge{11.14.3.1504} [Minecraft Forge] (forge-1.8-11.14.3.1504.jar) 
	UCHIJAAAA	RadixCore{1.8-2.0.4} [RadixCore] (RadixCore-1.8-2.0.4-universal.jar) 
	UCHIJAAAA	MCA{1.8-5.0.7} [Minecraft Comes Alive] (MCA-1.8-5.0.7-universal.jar) 
	UCHIJAAAA	cfm{3.4.8} [§9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.8-build1(1.8).jar) 
	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by HillustratedMike36** [comment] 2015-08-25 07:10
Would be better if you redid the title, seeing the issue occurs at night.

Speaking of crashes at night, there are other issues with this, so there isn't really a need for this duplicate issue.

On the bright side, you at least confirmed the existence (like some others) of this critical bug.

**Comment by WildBamaBoy** [comment] 2015-08-25 17:13
Closing duplicate of #521.

**Closed by WildBamaBoy** 2015-08-25 17:13 UTC
