### ISSUE TITLE
gifting not working with previously made save

### ISSUE THREAD

**Issue by snozzzz** [WildBamaBoy/minecraft-comes-alive#1190] opened 2019-07-30 00:48 UTC
had a previous save before adding mca because i got bored. when pressing the gift option it greys out all the other options like it should but no new window pops up. tried restarting game and reinstalling, same thing.

**Comment by WildBamaBoy** [comment] 2019-08-01 01:08
Does this also occur on a new world?

**Comment by duhnunes** [comment] 2019-08-05 21:13
As I understand it, after clicking on the "gift" option all other options are "disabled", right?
If so, you should have the gift you will give the villager in your hand, and then right-click to give the gift. To exit just press ESC

**Comment by WildBamaBoy** [comment] 2019-08-18 00:29
Closing for lack of information and unable to reproduce.

**Closed as completed by WildBamaBoy** 2019-08-18 00:29 UTC
